# Generated by Django 4.0.2 on 2022-02-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='overall',
            field=models.IntegerField(),
        ),
    ]
